DROP TABLE IF EXISTS HABILITER;

DROP TABLE IF EXISTS PLANIFIER;

DROP TABLE IF EXISTS PARTICIPER;

DROP TABLE IF EXISTS SEJOURNER;

DROP TABLE IF EXISTS LOGIN;

DROP TABLE IF EXISTS PERSONNE;

DROP TABLE IF EXISTS RAPPORTER;

DROP TABLE IF EXISTS CAMPAGNE;

DROP TABLE IF EXISTS LIEU;

DROP TABLE IF EXISTS APPARTENIR;

DROP TABLE IF EXISTS ECHANTILLON;

DROP TABLE IF EXISTS ESPECE;

DROP TABLE IF EXISTS BUDGET_MENSUEL;

DROP TABLE IF EXISTS NECESSITER;

DROP TABLE IF EXISTS HABILITATION;

DROP TABLE IF EXISTS UTILISER;

DROP TABLE IF EXISTS MATERIEL;

DROP TABLE IF EXISTS MAINTENANCE;

DROP TABLE IF EXISTS PLATEFORME;
